import sys
import streamlit as st
import datetime
import requests

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="🗺️ Atlas - AI Travel Planner",
    page_icon="🗺️",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("🗺️ Atlas - AI Travel Planner")

# initialize chat history message
if "messages" not in st.session_state:
    st.session_state.messages = []


st.header("How can I help you in planning a trip? Let me know where do you want to visit.")


with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="E.g., Plan a trip to goa for 5 days with a budget of Rs 5000")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # show user message
        # show thinking spinner while backend process the request
        with st.spinner("Planning your trip..."):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned")
            markdown_content = f"""# 🗺️ Atlas - AI Travel Planner
            # **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            # **CreatedBy:** Atlas 

            ---
            
            
            {answer}
            
            
            ---

            *This plan is generated by AI. Please verify all details before making travel arrangements.*
            """
            st.markdown(markdown_content)
        else:
            st.error("Error occurred while planning your trip." + response.text)

    except Exception as e:
        st.error("The response failed due to: " + str(e))